import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Navbar from '@/components/Navbar'
import Hero from '@/components/Hero'
import AboutWork from '@/components/AboutWork'
import CTAone from '@/components/CTAOne'
import About from '@/components/About'
import Products from '@/components/Products'
import Contact from '@/components/Contact'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${inter.className}`}>
        <Navbar />
        <Hero />
        <AboutWork />
        <CTAone />
        <About />
        <Products />
        <Contact />
      </main>
    </>
  )
}
